### PR TITLE
Implement nickel_open action

### LINKED ISSUE #26: menu hopping
One of my greatest irritations in latest firmwares is the removal of the "home" button from the reading screen.  Sometimes I have to hit return two or three times to get back to home.

Would it be possible to add items from the home screen menu (like home, my books, my articles, settings) so they could be added to the reading overflow menu?

### PR DESCRIPTION
**Pull request by geek1011**
closes #26

### CODE REVIEW

**Comment by geek1011** [comment]
I've tested this on 4.20.15015 with:

```
menu_item:main:tmp--discover_storefront:nickel_open:discover:storefront
menu_item:main:tmp--discover_wishlist:nickel_open:discover:wishlist
menu_item:main:tmp--library_library:nickel_open:library:library
menu_item:main:tmp--library_library2:nickel_open:library:library2
menu_item:main:tmp--library_all:nickel_open:library:all
menu_item:main:tmp--library_authors:nickel_open:library:authors
menu_item:main:tmp--library_series:nickel_open:library:series
menu_item:main:tmp--library_shelves:nickel_open:library:shelves
menu_item:main:tmp--library_pocket:nickel_open:library:pocket
menu_item:main:tmp--library_dropbox:nickel_open:library:dropbox
menu_item:main:tmp--reading_life_reading_life:nickel_open:reading_life:reading_life
menu_item:main:tmp--reading_life_stats:nickel_open:reading_life:stats
menu_item:main:tmp--reading_life_awards:nickel_open:reading_life:awards
menu_item:main:tmp--reading_life_words:nickel_open:reading_life:words
menu_item:main:tmp--store_overdrive:nickel_open:store:overdrive
menu_item:main:tmp--store_search:nickel_open:store:search
menu_item:main:tmp--1:nickel_open:
menu_item:main:tmp--2:nickel_open:test
menu_item:main:tmp--3:nickel_open:test:test
menu_item:main:tmp--4:nickel_open:library:test
menu_item:main:tmp--5:nickel_open:library:
```

**Comment by NiLuJe** [comment]
Will check it out later tonight, thanks ;).

**Comment by NiLuJe** [comment]
Working fine on my end (that library2 action is mighty fun. Nothing actually does it quite like that in the stock FW, right?) ;).

The obvious missing entry is a "Go back home", but after a look at the code and the symbols list, it kinda makes sense ;p.

Which still begs the question what the main menu's "Home" entry is doing (and/or the "Go back Home" in the reader)...

**Comment by geek1011** [comment]
> Which still begs the question what the main menu's "Home" entry is doing (and/or the "Back to Home" in the reader)...

That's actually pretty simple, but it doesn't involve the nav mixins. It's just MainWindowController::clear. I'd probably put it into nickel_misc though, as it fits better there.

**Comment by jackiew1** [comment]
@geek1011 ,

Any plans to add that 'Back to Home' menu item? I'd definitely use it. Not that that's likely to influence you over much. 😁

**Comment by geek1011** [comment]
@jackiew1: #39

**Pull request merged**
